spring:
  data:
    mongodb:
      uri: mongodb+srv://codeharsh108:Hrsptl646@cluster0.iziuq.mongodb.net/journaldb
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /journal